#!/bin/sh
set -eu

mkdir -p /etc/vfw /var/log/vfw
touch /var/log/vfw/vfw.log /var/log/vfw/cron.log

if [ "$1" = "configure" ] && [ -x /usr/local/bin/vfw ]; then
    if [ -r /etc/default/vfw ]; then
        . /etc/default/vfw
    fi
fi
